import React,{useEffect,useState}from'react';

const fallback={user:{name:'Vedant',gym:'SE7EN FIT Club',coins:7450,streak:7,caloriesLogged:1820,calorieGoal:2250,setsToday:12},shortcuts:['GYM','AI','CUT','BULK','QR'],workouts:[{id:'push',title:'Push Day',subtitle:'Chest shoulders triceps',duration:42,progress:76},{id:'pull',title:'Pull Power',subtitle:'Back biceps rear delts',duration:48,progress:58}],exercises:[{id:'bench',name:'Bench Press',muscle:'Chest',equipment:'Barbell',level:'Beginner',sets:4,reps:'8-12',rest:75,tempo:'3-1-1',kcal:96,steps:['Lie flat with eyes under bar','Grip wider than shoulders','Lower to mid chest','Press without bouncing'],warnings:['No bouncing','Keep hips stable','Control elbows']},{id:'pulldown',name:'Lat Pulldown',muscle:'Back',equipment:'Cable',level:'Beginner',sets:3,reps:'10-12',rest:60,tempo:'2-1-2',kcal:82,steps:['Sit tall','Pull elbows to ribs','Pause near chest','Return slowly'],warnings:['Avoid swinging','Do not pull behind neck','Control return']},{id:'squat',name:'Barbell Squat',muscle:'Legs',equipment:'Barbell',level:'Intermediate',sets:4,reps:'6-10',rest:90,tempo:'3-1-1',kcal:140,steps:['Brace core','Knees track toes','Controlled depth','Drive through mid foot'],warnings:['No knee cave','Neutral back','Use safe load']}],foods:[{id:'paneer',name:'Paneer Bowl',kcal:430,protein:28,carbs:32,fat:18},{id:'eggs',name:'Egg Bhurji',kcal:310,protein:24,carbs:8,fat:20},{id:'chicken',name:'Chicken Rice',kcal:560,protein:42,carbs:58,fat:16}],rewards:[{id:'streak',title:'7 day streak',value:700},{id:'referral',title:'Gym referral',value:1500},{id:'protein',title:'Protein goal',value:300}],plans:[{id:'starter',name:'Starter',price:199,badge:'Start'},{id:'pro',name:'Pro Beast',price:399,badge:'Popular'},{id:'elite',name:'Elite',price:999,badge:'Elite'}],members:[{id:'m1',name:'Aarav S.',plan:'Pro Beast',progress:82,status:'Active',commission:100}],payments:[{id:'SF-1007',user:'Aarav S.',amount:399,commission:100,status:'Pending'}]};

function useAppData(){const[data,setData]=useState(fallback);useEffect(()=>{fetch('/api/app').then(r=>r.ok?r.json():fallback).then(setData).catch(()=>setData(fallback))},[]);return data}
function Top({data}){return <header className="appTop"><div><b className="logo">SE7EN<span>FIT</span></b><p>{data.user.gym}</p></div><button className="profile">{data.user.name[0]}</button></header>}
function Bar({value}){return <div className="bar"><i style={{width:`${value}%`}}/></div>}
function Stat({label,value}){return <div className="stat"><b>{value}</b><span>{label}</span></div>}
function Chip({children,onClick,active}){return <button onClick={onClick} className={active?'chip active':'chip'}>{children}</button>}

function Home({data,setTab}){const main=data.workouts[0];return <section className="screen"><Top data={data}/><div className="search">Search workout, food, trainer, gym</div><div className="avatarLine">{data.shortcuts.map(x=><button key={x}>{x}</button>)}</div><div className="hero"><div><small>TODAY WORKOUT</small><h1>{main.title}</h1><p>{main.subtitle} · {main.duration} min</p><button onClick={()=>setTab('guide')}>Start Workout</button></div><div className="coin"><b>{main.progress}%</b><span>ready</span></div></div><div className="stats"><Stat label="day streak" value={data.user.streak}/><Stat label="kcal logged" value={data.user.caloriesLogged}/><Stat label="sets today" value={data.user.setsToday}/></div><h3 className="sectionTitle">Quick actions</h3><div className="quick"><button onClick={()=>setTab('guide')}><b>Workout Guide</b><span>animated form</span></button><button onClick={()=>setTab('food')}><b>Food Scan</b><span>calorie AI</span></button><button onClick={()=>setTab('trainer')}><b>AI Trainer</b><span>ask coach</span></button><button onClick={()=>setTab('rewards')}><b>Rewards</b><span>coins</span></button></div><h3 className="sectionTitle">Weekly split</h3><div className="week">{['Push','Pull','Legs','Rest','Upper','Lower','Core'].map((x,i)=><span className={i===0?'on':''} key={x}>{x}</span>)}</div></section>}

function Guide({data}){const[filter,setFilter]=useState('Chest');const filtered=data.exercises.filter(e=>filter==='All'||e.muscle===filter);const[active,setActive]=useState(data.exercises[0]);const current=active||data.exercises[0];return <section className="screen"><h2 className="pageTitle">Workout Guide</h2><div className="chips">{['All','Chest','Back','Legs','Shoulders','Arms'].map(x=><Chip key={x} active={filter===x} onClick={()=>{setFilter(x);const n=data.exercises.find(e=>x==='All'||e.muscle===x);if(n)setActive(n)}}>{x}</Chip>)}</div><div className="exerciseHero"><div className="motion"><span/><i/></div><small>{current.muscle} · {current.equipment}</small><h1>{current.name}</h1><p>{current.sets} sets · {current.reps} reps · {current.rest}s rest</p><div className="metricRow"><Stat label="tempo" value={current.tempo}/><Stat label="kcal" value={current.kcal}/></div><h3>Steps</h3>{current.steps.map((s,i)=><p className="step" key={s}>{i+1}. {s}</p>)}<h3>Warnings</h3>{current.warnings.map(w=><p className="warn" key={w}>{w}</p>)}</div><h3 className="sectionTitle">Library</h3>{filtered.map(e=><button className="listItem" key={e.id} onClick={()=>setActive(e)}><div><b>{e.name}</b><span>{e.muscle} · {e.level}</span><Bar value={e.kcal/1.5}/></div><em>{e.sets}x</em></button>)}</section>}

function Food({data}){const[meal,setMeal]=useState(data.foods[0]);return <section className="screen"><h2 className="pageTitle">Calories</h2><div className="scanCard"><b>SCAN FOOD</b><p>Upload food photo or select meal. API endpoint is ready for AI vision integration.</p></div><div className="chips">{data.foods.map(f=><Chip key={f.id} active={meal.id===f.id} onClick={()=>setMeal(f)}>{f.name}</Chip>)}</div><div className="foodResult"><small>ESTIMATED RESULT</small><h1>{meal.kcal} kcal</h1><p>{meal.name}</p><div className="metricRow"><Stat label="protein" value={meal.protein+'g'}/><Stat label="carbs" value={meal.carbs+'g'}/><Stat label="fat" value={meal.fat+'g'}/></div></div><h3 className="sectionTitle">Today</h3><div className="listItem"><div><b>Calories</b><span>{data.user.caloriesLogged}/{data.user.calorieGoal}</span><Bar value={80}/></div></div></section>}

function Trainer(){const[msg,setMsg]=useState('Build chest workout');const[chat,setChat]=useState(['Ask workouts, diet, form or recovery.']);async function send(){if(!msg)return;const r=await fetch('/api/trainer/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg})}).then(x=>x.json()).catch(()=>({reply:'Track sets and recover well.'}));setChat([...chat,msg,r.reply]);setMsg('')}return <section className="screen"><h2 className="pageTitle">AI Trainer</h2><div className="chatBox">{chat.map((x,i)=><p className={i%2?'me':'bot'} key={i}>{x}</p>)}</div><div className="send"><input value={msg} onChange={e=>setMsg(e.target.value)}/><button onClick={send}>Send</button></div></section>}
function Rewards({data}){return <section className="screen"><h2 className="pageTitle">Rewards</h2><div className="wallet"><small>SE7EN COINS</small><h1>{data.user.coins}</h1><p>Earn from workouts, referrals and diet streaks.</p></div><div className="rewardGrid">{data.rewards.map(r=><div className="reward" key={r.id}><b>+{r.value}</b><span>{r.title}</span></div>)}</div><h3 className="sectionTitle">Plans</h3>{data.plans.map(p=><div className="listItem" key={p.id}><div><b>{p.name}</b><span>{p.badge} · owner commission {Math.round(p.price*.25)}</span></div><em>{p.price}</em></div>)}</section>}
function Owner({data}){const revenue=data.payments.reduce((s,p)=>s+p.amount,0);const commission=data.payments.reduce((s,p)=>s+p.commission,0);return <section className="screen"><h2 className="pageTitle">Gym Owner</h2><div className="hero owner"><div><small>REFERRAL CODE</small><h1>GYM25</h1><p>Track members, payments and 25 percent commission.</p></div><button>QR</button></div><div className="stats"><Stat label="revenue" value={revenue}/><Stat label="commission" value={commission}/></div>{data.members.map(m=><div className="listItem" key={m.id}><div><b>{m.name}</b><span>{m.plan} · {m.status}</span><Bar value={m.progress}/></div><em>{m.commission}</em></div>)}</section>}
function Bottom({tab,setTab}){return <nav className="bottom">{['home','guide','food','trainer','rewards','owner'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'on':''}>{x}</button>)}</nav>}
export default function App(){const data=useAppData();const[tab,setTab]=useState('home');const pages={home:<Home data={data} setTab={setTab}/>,guide:<Guide data={data}/>,food:<Food data={data}/>,trainer:<Trainer/>,rewards:<Rewards data={data}/>,owner:<Owner data={data}/>};return <main className="appReal">{pages[tab]}<Bottom tab={tab} setTab={setTab}/></main>}
